### ISSUE TITLE
voidmei hash needs update

### ISSUE THREAD

**Issue by tu10ng** [Lutra-Fs/scoop-bucket#1]
## Bug Report

**Package Name:** voidmei

### Current Behaviour

current hash is "hash": "68aaf9d239d56614e11b0a839a6202f80df9b235652d9ef346df843040bf51dd",

### Expected Behaviour

expected hash is "69aa99451cb62ba9457bba0e6559a3e9abf3c257836be6d2552f3fd316700ad0"

### Additional context/output

在推出voidmei 1.560版本后, voidmei更新了release里文件的内容, 因此hash改变了, 但是没有触发scoop的自动更新.

[https://github.com/matrixsukhoi/voidmei/issues/20](https://github.com/matrixsukhoi/voidmei/issues/20)

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by Lutra-Fs** [comment]
你好，感谢你的issue。可以看到voidmei的确在本次发布后3个小时内又进行了一次文件覆盖，我将手动更新hash值。scoop仓库的自动更新原理依赖于版本的变化，对于版本号不变更，仅重新提交releases文件的热更新方式目前没有比较好的解决方案。
